apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "servicenow-kafka-bridge.fullname" . }}
  labels:
    {{- include "servicenow-kafka-bridge.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
